CXXFLAGS=-std=c++11 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant
//CFLAGS=-std=c99 -pedantic -Wall -Wextra -Werror -ansi -Wwrite-strings

main: ChainedHashTable.cpp
	echo ------------compiling main.cpp to create executable program main--------------
	g++ -ggdb $(CXXFLAGS) ChainedHashTable.cpp -o main
