CXXFLAGS=-std=c++11 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant -ggdb
//CFLAGS=-std=c99 -pedantic -Wall -Wextra -Werror -ansi -Wwrite-strings

main: main.cpp TreeNode.cpp
	echo ------------compiling main.cpp to create executable program main--------------
	g++ -ggdb $(CXXFLAGS) main.cpp TreeNode.cpp -o main
