CXXFLAGS=-std=c++11 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant -Weffc++
//CFLAGS=-std=c99 -pedantic -Wall -Wextra -Werror -ansi -Wwrite-strings

main: main.cpp UnorderedLinkedList.cpp UnorderedArrayList.cpp
	echo ------------compiling main.cpp to create executable program main--------------
	g++ -ggdb $(CXXFLAGS)  main.cpp UnorderedLinkedList.cpp UnorderedArrayList.cpp -o main



